import { Text, Linking } from 'react-native';

export type domainInfo = {
  info: string;
  strategy: string;
};

export const domainInformation = {
  physical: {
    info:
      "This app asks you to rate yourself on measures of physical health. Several good measures of physical health are appetite, quality of sleep, exercise, level of energy, use of medication or other drugs, and physical illness. \n\nWhy is physical health important? The answer to this question is obvious, but here's one a lot of people don't consider. The importance of sleep. For example, when you lack sleep, you will tend to have lower energy and perhaps try to compensate by drinking more coffee or eat sugar to keep you stimulated. You might even use sleep aids to help you sleep but over the long run, medications are an artificial compensation for sleep hygiene or sleep hormones in trouble. When you get too much sleep, you will probably feel groggy during the day, or you might get a kink in your neck or back from lying around so long. Small fluctuations are common and help keep your mental and emotional health balanced. Large fluctuations in sleep are often seen in depressed people who sleep too much or not enough. \n\nAs you can see, sleep is vital for your well-being during the day. Like the other aspects of physical health like exercise and appetite, the physical acts of sleep, exercise, and eating can hugely impact other types of health that you want to improve.",
    strategy:
      'A few strategies for improving sleep are: \n   • go to sleep at roughly the same time every night \n   • get exposure to light and exercise early in the day\n   • for other information on sleep hygiene, see \n ',
  },
  mental: {
    info:
      "One way of defining mental health is through measures like the ability to concentrate, solve problems, and communicate clearly and effectively. Another definition is the absence of mental illness. Perhaps a better definition includes the aspects of clarity of mind, solution- orientedness, and positive outlook on one's life, presence of mind, and motivation towards some social benefit or life purpose. Again, one health system or dimension impacts the others. The ability to notice unintentional alterations of states of consciousness, such as dozing off (hopefully not “at the wheel”) or having nightmares or panic attacks, suggests the beginning of healing from these difficulties.",
    strategy:
      "The central recommendation for all difficulties associated with health is to strive for moderation, balance, or harmony. There are several ways to do this. The upgraded version of this app being developed is to provide exercises which hinge around the harmony principle. \nFounded in psychological science, recommendations for improving mental health include:\n   • Deep breathing and progressive muscle relaxation   • Mindfulness meditation (as in Tara Brach's amazing guided meditation collection)\n   • Floating\n   • Positive psychology tools\n   • Explorations of how the body's energy changes and heals from skillful touch (as in physiotherapy, massage, chiropractic, integrative energy healing, etc.),\n   • Emotional attunement (as in couple's relationships)\n   • Novel technologies (as in MUSE)\n   • Contact a psychologist or counsellor [provide link to contact therapist page]",
  },
  social: {
    info:
      'We touched on the overlap of social health with emotional Health Circle. This is evident in social anxiety. Other measures of social health include: how we feel about our close relationships, how well we get along and can depend on family members, and how well we socialize with people outside our close relationships and family. \n\nAll these areas of social health have importance, especially when we are alone. Being alone can be just fine, as we do need some time to ourselves, for a sense of independence and to learn who we are inside. But when being alone starts to feel lonely, research has shown a higher risk of death. The explanation for this is unclear and research is being done to help understand the link between loneliness and mortality. Clearly, there is a yearning for connection with others, for helping one another, and to be helped and loved by others. Without that emotional and physical connection to those we trust moves us closer to losing the purpose of being part of the larger group that we hope would rally around us when we are ailing. Without that support, if we are very sick, it can get more and more difficult to do things on our own. We need one another.',
    strategy:
      "Asking oneself these questions are strategies to get us thinking and acting to improve our social health. How is your social health? Do you have regular and pleasant interactions with friends, family, and a spouse or beloved partner? Do you take part in community activities, such as volunteering or enjoying music with others? Do you have a job, go to school, or engage in learning new things from others? These are connections that can be very rewarding and bring balance to our self-time. \n\nOther strategies include: \n   • Text, email, or call a friend and invite them to talk or to participate in some activity. Even online is better than no contact at all. At least you get to see them.\n   • Online or off, try for face-to-face contact.\n   • Get a dog! Dogs get us out walking or (if the dog is small) wheelchairing. They evoke chats between strangers, family, and friends alike about their mutual interest in dogs. Dog-owners have been shown in research to be generally healthier in all health dimensions. Dogs also encourage empathy, patience, and new learning – such as dog training skills.\n   • Notice feelings of avoidance, irritability, or resentment. Try to stay open to these feelings because suppressing them can perpetuate the cycle. \n   • Forgive others when they don't reply to you. Forgive them for having a life. They probably have other things on. Don't take other people's lives as an insult against you. \n   • Forgive yourself when you don't reply to others. Forgive yourself for having the life you do. \n   • Refer to recommendations in the mental, emotional, and social dimension [provide links to those recommendations]\n   • Exploring your positive feelings about someone can help you sort out how to repair the relationship. Write them down and remind yourself of them.\n   • Repair the relationship by reaching out and remember it's okay to have differing points of view. Start slowly and stay willing to talk it through.\n   • Try to reach understanding of the other's point of view. Don't focus on reaching agreement. Seek to understand how they came to this place and offer to listen to that. Ask them to do the same.\n   • Contact a psychotherapist or counsellor for support [link to contact therapist page]",
  },
  emotional: {
    info:
      "Several ways to measure emotional health are feelings such as anxiety, compassion, happiness, anger, empathy, joy, sorrow, creativity, grief, and love. Primary emotions are fear and sadness. These are often expressed as disappointment, humiliation, and anxiety. For most people, negative emotions are often triggered by traumatic experiences, while positive emotions are brought about by feeling appreciated or valued. We are trained to avoid negative emotions very early in life. Parents or teachers tell us not to cry or try to make us not be so upset by telling us, “Oh, it's not so bad as that!” Trouble is, they are missing the point. These comments are invalidating. Research has shown that invalidating environments can cause psychological injury. The more invalidating, the more injury is caused. \n\nHuman development means we change as we move from conception through birth, childhood, teen and adult years, towards death. Change can be scary. But it can also be exciting. One way to cope with anxiety is to recognize that it represents the impulse to fear a threatening situation. But that threat is a perception. Just because social anxiety is the second most common fear second only to death doesn't mean we can't use it to our advantage. Social anxiety ties in with almost every other type of fear – of being judged by others, of being talked about by others behind our backs, and trying to deny our humanity and appear perfectly free of mistakes. What's worse is we'll die being judged and talked about by others or being eaten by a tiger.",
    strategy:
      "   • Educate yourself about the effects of invalidation \n   • Is that really a tiger? Consider whether the situation is really as threatening as we think it is. \n   • Seek positive things in the situation. \n   • Write your own epitaph – what do you want people to remember you for? • Remember your mindfulness skills, notice the negative story floating away on a cloud.  • Don't get caught up in the story \n   • Journal all the positive things that happened today \n   • List 5 things you are grateful for \n   • Define a path of your own, even if others disagree \n   • Get other people's views of your troubles by sharing them with people you trust \n   • Seek psychotherapy or counselling [provide link to contact therapist page]",
  },
  spiritual: {
    info:
      "Consider questions like: How well do you make choices and act according to your beliefs and values? How open you are to others having the same or differing beliefs from your own? How and why life is meaningful to you? How can I live my best life? \n\nIf any of these questions feel engaging or important, or they touch your heart, then spirituality is an area of health you could benefit from exploring. \n\nLike any other subject, spirituality isn't important to everyone. If it isn't important to you, then you may be missing something. Spirituality can point us to our purpose in life. Spirituality is more than the fact that we were born and we will die. It can point us to a set of principles or values to live by and provide a springboard to get involved with other people that stand for those principles. It can provide a sense of belonging to a community. We don't have to call it spirituality or religion. We could call it “integrative health” or “healthy values”. Search for a word that describes this health dimension best for you.",
    strategy:
      "Research has shown a focus on spirituality is often associated with improved well-being. But what can reduce well-being is feeling forced to believe something we are dead-set against. That can make us feel invalidated. Then the question can be how to work our way through situations like that.\n   • Do we simply avoid challenges to our belief systems?\n   • Do we engage in conversations about our values?\n    • What are our values anyway? What do we value about ourselves, our health, other people, their health?\n    • What we value and believe are the foundations for feelings of injustice, towards ourselves and others. How do we feel about injustice in the world? List the sources of injustice we feel strongly about. Which ones do we point to first? Last? Invite yourself to stay open to the feelings that come up here.\n   • Take a risk and invite someone else into your conversations with yourself about these issues? \n\nBesides asking questions and talking, other strategies include taking action:\n   • Participate in a cause for social justice (e.g., help the homeless, volunteer to help animals, do something to support Earth's ecosystem)\n   • Contact a psychologist or therapist [provide link to contact therapist page]",
  },
};
