import { Text, Linking } from 'react-native';

export type domainInfo = {
  info: string;
  strategy: string;
};

export const domainInformation = {
  physical: {
    info:
      "Health Circles asks you to rate yourself on measures of your physical health.\nMeasures of physical health include appetite, quality of sleep, exercise, level of energy, use of medication or other drugs, and physical illness. \n\nYou may ask, why is physical health important?\nThe answer to this question is clear, but here's one thing that a lot of people do not consider. The importance of sleep.\nFor example, when you lack sleep you will tend to have lower energy and perhaps try to compensate by drinking more coffee or eat more sugar to keep you stimulated. You might even use sleep aids to help you sleep. However, over time since medications are an artificial compensation for sleep hygiene your sleep hormones are then in trouble. When you get too much sleep, you will probably feel groggy during the day, you might get a kink in your neck or back from lying around so long. Small fluctuations are common and help keep your mental and emotional health balanced. Large fluctuations in sleep are often seen in people who are depressed, sleep too much or not enough. \n\nAs you can see, sleep is vital for your well-being during the day. Like the other aspects of physical health such as exercise and appetite; the physical acts of sleep, exercise, and eating can hugely impact other dimensions of health that you want to improve.",
    strategy:
      'Strategies for improving sleep: \n• Go to sleep at roughly the same time every night \n• Get exposure to light and exercise early in the day\n• For more information on sleep hygiene, check out information\n ',
  },
  mental: {
    info:
      "One way of being able to define mental health is through various skills such as the ability to concentrate, solve problems, and communicate clearly and effectively. Perhaps a better definition includes the aspects of clarity, solution- orientedness, positive outlook on one's life, presence of mind, and motivation towards some social benefit or life purpose.\n\nOne health system or dimension impacts the others. The ability to notice unintentional alterations of states of consciousness, such as dozing off or having nightmares/panic attacks, suggest the beginning of healing from these difficulties.",
    strategy:
      "The central recommendation for difficulties associated with health is to strive for moderation, balance, and/or harmony. There are several ways to do this, the upgraded version of this application being developed is to provide exercises which tie to the harmony principle. \n\nRecommendations for improving mental health include:\n• Deep breathing and muscle relaxation\n• Mindfulness meditation \n• Floating\n• Positive psychology tools\n• Explorations of how the body's energy changes and heals from skillful touch (ie: physiotherapy, massage, chiropractic, integrative energy healing, etc.),\n• Emotional attunement \n• Novel technologies \n• Contact a psychologist or counsellor ",
  },
  social: {
    info:
      'There is an overlap between social health and emotional health domains. This is evident in social anxiety.\n\nOther measures of social health include:\n• How we feel about our close relationships.\n• How well we get along and can depend on family members.\n• How well we socialize with people outside our close relationships and family. \n\nAll of these areas of social health have importance especially when we are alone. Being alone can be just fine. Everyone needs time for themselves for a sense of independence and to learn who they are. But when being alone starts to feel lonely, research has shown a higher risk of death. The explanation for this is unclear, research is being done to help understand the link between loneliness and mortality. There is a clear yearning for connection with others, helping one another, and to be helped and loved by one another. Without that emotional and physical connection to those we trust moves us closer to losing the purpose of being part of the larger group that we hope would rally around us when we are ailing. Without that support, it can get more and more difficult to do things on our own.\n\n We all need one another.',
    strategy:
      "How is your social health?\nDo you have regular and pleasant interactions with friends, family, and a spouse or beloved partner?\nDo you take part in community activities, such as volunteering or enjoying music with others?\nDo you have a job, go to school, or engage in learning new things from others?\nAsking oneself these questions are strategies to get us thinking and actively working to improve our social health. These are connections that can be very rewarding and bring balance to our self-time. \n\nOther strategies include: \n• Text, email, or call a friend and invite them to talk or to participate in some activity. Even online is better than no contact at all. At least you get to see them.\n• Online or offline, try for face-to-face contact.\n• Get a dog! Dogs get us out walking and evoke chats between new people, family, and friends alike about their mutual interest in dogs. Dog-owners have been shown in research to be generally healthier in all health domains. Dogs also encourage empathy, patience, and new learning; such as dog training skills.\n• Stay open to feelings rather than supressing them as that can perpetuate the cyle. Notice feelings of avoidance, irritability, or resentment.  \n• Be empathetic, forgive others when they don't reply to you. They probably have other things on. Don't take other people's lives as a personal insult against you. \n• Do not feel guilty when you don't reply to others. Do not feel guilty for having the life you do. \n• Refer to recommendations in the mental, emotional, and social dimensions.\n• Exploring your positive feelings about someone can help you sort out how to repair the relationship. Write them down and remind yourself of them.\n• Repair relationships by reaching out and remember it's okay to have differing points of view. Start slowly and stay willing to talk it through and understand a different perspective.\n• Try to reach an understanding of the other's point of view. Don't focus on reaching agreement. Seek to understand how they came to this place and offer to listen to that. Ask them to do the same.\n• Contact a psychotherapist or counsellor for support.",
  },
  emotional: {
    info:
      "To measure emotional health are through feelings such as anxiety, compassion, happiness, anger, empathy, joy, sorrow, creativity, grief, and love.\nPrimary emotions are fear and sadness. These are often expressed as disappointment, humiliation, and anxiety. For most people, negative emotions are often triggered by traumatic experiences, while positive emotions are brought about by feeling appreciated or valued.\nWe are trained to avoid negative emotions very early in life. Parents or teachers tell us not to cry or try to make us not be so upset by telling us, “Oh, it's not so bad as that!” Trouble is, they are missing the point. These comments are invalidating. Research has shown that invalidating environments can cause psychological injury. The more invalidating, the more injury is caused. \n\nHuman development means we change as we move through different stages of life. Change can be scary. But it can also be exciting.\n\nOne way to cope with anxiety is to recognize that it represents the impulse to fear a threatening situation. But that threat is a perception. Just because social anxiety is the second most common fear, second only to death doesn't mean we can't use it to our advantage. Social anxiety ties in with almost every other type of fear; of being judged by others, of being talked about by others behind our backs, and trying to deny our humanity and appear perfectly free of mistakes.",
    strategy:
      "• Educate yourself about the effects of invalidation. \n• Consider whether the situation is really as threatening as we think it is. \n• Seek a positive perspective in situations. \n• Write your own epitaph – what do you want people to remember you for?\n• Remember your mindfulness skills, notice the negative story floating away on a cloud.\n• Journal all the positive things that happened today. \n• List 5 (or more) things you are grateful for. \n• Define a path of your own, even if others disagree. \n• Share your worries with people you trust; confide in those people. \n• Seek psychotherapy or counselling " ,
  },
  spiritual: {
    info:
      "Consider questions such as:\n•How well do you make choices and act according to your beliefs and values?\n•How open you are to others having the same or differing beliefs from your own?\n•How and why life is meaningful to you?\n•How can I live my best life? \n\nIf any of these questions feel engaging or important, or they touch your heart, then spirituality is an area of health you could benefit from exploring. \n\nLike any other subject, spirituality isn't important to everyone. However, not everyone sees that spirituality can point us to our purpose in life. Spirituality is more than the fact that we were born and we will die. It can point us to a set of principles or values to live by and provide a springboard to get involved with other people that stand for those principles. It can provide a sense of belonging to a community. We don't have to call it spirituality or religion. We could call it “integrative health” or “healthy values”.\n Search for a word that describes this health dimension best for you.",
    strategy:
      "Research has shown the focus on spirituality is often associated with improved well-being. But what can reduce well-being is feeling forced to believe something we simply do not believe in. That can make us feel invalidated.\nThen the question can be how to work our way through situations like that.\n• Do we simply avoid challenges to our belief systems?\n• Do we engage in conversations about our values?\n• What are our values anyway?\n• What do we value about ourselves, our health, other people, their health?\n• What we value and believe are the foundations for feelings of injustice, towards ourselves and others. How do we feel about injustice in the world?\n•List the sources of injustice we feel strongly about. Which ones do we point to first? Last?\n\nInvite yourself to stay open to the feelings that come up here.\n\n• Take a risk and invite someone else into your conversations with yourself about these questions? \n\nBesides asking questions and talking other strategies include taking action in ways such as:\n• Participating in a cause for social justice (ie: help the homeless, volunteer to help animals, do something to support Earth's ecosystem)\n• Contact a psychologist or therapist",
  },
};
