name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      working-directory: ./client
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install
        run: |
          yarn install
          npm install -g mocha
          npm install -g typescript
          npm install -g ts-node
          npm install -g jest
          npm install -g ts-jest
          npm install -g jest-expo
        working-directory: ${{env.working-directory}}

      - name: Run tests
        run: yarn test
        working-directory: ${{env.working-directory}}
